-- importing lua config from the lua folder
require "kevin.options"
require "kevin.keymaps"
require "kevin.plugins"
require "kevin.colors"
require "kevin.cmp"
require "kevin.tree"
require "kevin.lsp"
require "kevin.telescope"
require "kevin.treesitter"
require "kevin.lualine"
require "kevin.bufferline"
require "kevin.autopairs"
require "kevin.toggleterm"
require "kevin.comment"
require "kevin.git"
